Month 7/step 1
shvkn/react-burger pull request #4
Opened 2022-10-25 15:45 UTC by shvkn

Сверстал макет первой страницы по макету, с использованием библиотеки компонентов https://yandex-practicum.github.io/react-developer-burger-ui-components/

2022-10-25 16:26 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app. (App.test.tsx)

- удалите файл `types.js`, который находится в папке `utils`.

- Исправьте работу с propTypes (Отметил в коде).

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +    supplements: [
**Можно лучше:** Лучше назвать `ingredients` - так будет более корректно.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/app/App.tsx
> +  const state = {
**Надо исправить:** Моковые данные, лучше вынести в константу в отдельный файл. Имена констант принято записывать в стиле UPPER_CASE.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/nav-button/nav-button.jsx
> +    </button>
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например
```html
<a href="#" class="......">
   <BurgerIcon type="primary" /> Конструктор
</a>
```
В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/nav-button/nav-button.jsx
> +    <button className={`pt-4 pl-5 pb-4 pr-5 ${styles.button} ${extraClass}`.trim()}>
**Надо исправить:** Тут лучше сделать проверку, либо сделать дефолтное значение `extraClass = ''`.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/nav-button/nav-button.jsx
> +NavButton.propTypes = {
**Надо исправить:**: 

Описаны не все пропсы, которые используются в компоненте. 

В описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/app-main/app-main.jsx
> +export default AppMain;
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +}
**Надо исправить:** Лучше вынести в подпапку components. 
А также не стоит дробить целый ингредиент на пропсы, передавайте цельный объект.
И для этого компонента так же нужно описать PropTypes.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +BurgerConstructor.propTypes = {
**Надо исправить:** 

Описаны не все пропсы, которые используются в компоненте.

А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +  />
**Надо исправить:** Не стоит так сильно дробить верстку компонента, пишите напрямую в jsx.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    </List>
**Надо исправить:** Похожее замечание, про слишком большое дробление компонента, было ниже.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/burger-ingredient/burger-ingredient.jsx
> +BurgerIngredient.propTypes = {
**Можно лучше:** 
Лучше не дробить ингредиент на множество пропсов, а использовать сразу цельный объект.

В описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +};
**Надо исправить:** Лучше вынести в папку `utils`, в файлик: `prop-types.js`.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +BurgerIngredients.propTypes = {
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте.

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/list/list.jsx
> +function List({children, listExtraClass, itemExtraClass}) {
**Можно лучше:** Немного не понимаю, зачем для 1 html элемента создавать отдельный компонент.

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/list/list.jsx
> +List.propTypes = {
**Надо исправить**

В описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2022-10-25 16:26 UTC, ArslanDev666 commented on src/components/nav-menu/nav-menu.jsx
> +function NavMenu({children, rightContent}) {
**Можно лучше:** Описал похожую проблему в компонент `list.jsx`.

2022-10-27 15:36 UTC, shvkn commented
Выпиленны лишние компоненты List, NavButton, NavMenu, Price
Настроил eslint (airbnb) + prettier

2022-10-28 02:57 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличая работа. Был проведён хороший рефакторинг.

### **Вы молодец! Приступайте к финальному этапу задания.**

### **Есть несколько замечаний, которые нужно будет исправить:**

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app. (App.test.tsx)

- Исправьте работу с propTypes (Отметил в коде).

### **Сделает код лучше:**

- я бы не стал так сильно себя ограничивать линтерами, например правило `no-underscore-dangle` в eslint, не всегда полезно.

2022-10-28 02:57 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +  ingredients: PropTypes.arrayOf(ingredientPropTypes).isRequired,
**Нужно исправить:** 

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

2022-10-28 02:57 UTC, ArslanDev666 commented on src/utils/prop-types.js
> +  ingredients: PropTypes.arrayOf(PropTypes.string).isRequired,
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

2022-10-28 02:57 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +              <li key={key} className={`mt-4 mb-4 ${styles.ingredient}`}>
**Надо исправить:** Давайте пока оставим, в качестве значения key - индекс массива. Сейчас нам нет смысла усложнять данный функционал. В будущем спринте (когда начнёте проходить redux), у вас будет возможность это исправить.))

2022-10-28 02:57 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +            const { image, name, price } = ingredients.find(({ _id: id }) => id === _id);
**Надо исправить:** Лучше не делать поиск в самом `jsx`. Можно до рендера сделать фильтрацию, и потом спокойно выводить ингредиенты. 

```js
  const filteredIngredients = ingredients.filter(({ _id: id }) => state.ingredients.includes(id));
```

2022-10-28 02:57 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  ingredients: PropTypes.arrayOf(ingredientPropTypes).isRequired,
**Надо исправить:** Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

```js
  ingredients: PropTypes.arrayOf(ingredientPropTypes.isRequired).isRequired,
```

2022-10-28 07:00 UTC, shvkn commented
1. Вынес из рендера JSX логику работы с массивами.
2. Убрал из линтера `airbnb-config`
3. Вернул `index` в качестве ключа для рендера "ингридиетов" в `BurgerConstructor`
4. Добавил `isRequired` в недостающие места цепочек PropTypes
5. Убрал total из константы `BURGER_STATE_MOCKUP`

2022-10-28 07:10 UTC, shvkn commented
P.S. Отправил исправления к первой части на ревью не увидев "Приступайте к финальному этапу задания"

2022-10-28 10:43 UTC, ArslanDev666 commented
> P.S. Отправил исправления к первой части на ревью не увидев "Приступайте к финальному этапу задания"

Окей, отменю без потери итерации))

2022-11-06 09:59 UTC, merged